<?php

namespace Notimeo\BlocksBundle\Repository;

/**
 * BlockRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
