easy_admin:
    entities:
        Block:
            class: Notimeo\BlocksBundle\Entity\Block
            list:
                fields:
                    - title
                    - updateDate
            form:
                fields:
                    - title
                    - { property: content, type: ckeditor }
                    - region
        BlockRegion:
            class: Notimeo\BlocksBundle\Entity\BlockRegion
            list:
                fields:
                    - name
            form:
                fields:
                    - name