#app:
#    resource: "@AppBundle/Resources/config/routing.yml"
easy_admin_bundle:
#    resource: "@EasyAdminBundle/Controller/"
    resource: "@CoreBundle/Controller/NotimeoAdminController.php"
    type:     annotation
    prefix:   /{_locale}/admin
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%locales_req%'

notimeo_core_bundle:
    resource: .
    type: notimeo_core_routes

notimeo_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"

#notimeo_banners_bundle:
#    resource: "@BannersBundle/Resources/config/routing.yml"