security:
    providers:
        db_provider:
            entity:
                class: Notimeo\UserBundle\Entity\User
                property: username
    firewalls:
#        main:
#            pattern:    ^/
#            http_basic: ~
#            provider: db_provider
        dev:
#            provider: db_provider
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/(.*)+/admin, roles: ROLE_ADMIN }
    encoders:
        Notimeo\UserBundle\Entity\User:
            algorithm: bcrypt