# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    form.type.translatable:
        class: Notimeo\PageBundle\Form\TranslatableType
        arguments: [ '@doctrine.orm.default_entity_manager', '@validator', '%locales%', '%locale%' ]
        tags:
            - { name: form.type, alias: translatable }
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension