<?php

namespace Notimeo\PageBundle\Repository;

/**
 * PageLocaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageFileRepository extends \Doctrine\ORM\EntityRepository
{
}
