easy_admin:
    entities:
        BannerCategory:
            class: Notimeo\BannersBundle\Entity\BannerCategory
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: "%app.path.product_images%" }
            list:
                fields:
                    - name
            new:
                form_options: { validation_groups: ['Default', 'new'] }
            form:
                fields:
                    - name
                    - property: 'banners'
                      label: 'Banners'
                      type: 'collection'
                      type_options:
                          entry_type: 'Notimeo\BannersBundle\Form\Type\BannerType'
                          by_reference: false
                          error_bubbling: false