#easy_admin:
#    entities:
#        Product:
#            class: AppBundle\Entity\Product
#        ProductCategory:
#            class: AppBundle\Entity\Category
#        User:
#            class: AppBundle\Entity\User