easy_admin:
    entities:
        Page:
            class: Notimeo\PageBundle\Entity\Page
            list:
                fields:
                    - title
                    - { property: 'image', type: 'image', base_path: "%app.path.product_images%" }
                    - updateDate
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: "%app.path.product_images%" }
#            new:
#                form_options: { validation_groups: ['Default', 'add_page'] }
            edit:
                form_options: { validation_groups: ['Default', 'xxxx'] }
            form:
#                form_options: { validation_groups: ['Default'] }
                fields:
                    - isPublished
                    - property: 'locales'
                      label: 'Content translations'
                      type: 'collection'
                      type_options:
                          entry_type: 'Notimeo\PageBundle\Form\Type\PageLocaleType'
                          error_bubbling: false
                          by_reference: false
                    - property: 'pageFiles'
                      type: 'collection'
                      type_options:
                          entry_type: 'Notimeo\PageBundle\Form\Type\MyFileType'
                          by_reference: false
                          error_bubbling: false