services:
#    my.listener:
#        class: Notimeo\PageBundle\EventListener\PageAuthorUpdater
#        tags:
#            - { name: doctrine.event_listener, event: preUpdate }
#        arguments: ["@security.token_storage"]
    my.subscriber:
        class: Notimeo\PageBundle\EventListener\PageAuthorSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments: ["@security.token_storage"]
    form.type.page.locale:
        class: Notimeo\PageBundle\Form\Type\PageLocaleType
        tags:
            - { name: form.type, alias: notimeo_pagebundle_pagelocale }
        arguments: ['%locales%']